version: "3.9"
services:
  app:
    build: ../
    ports:
      - "8000:8000"
    networks:
        - backend
  mongo:
      image: mongo:5.0.3
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
      volumes:
        - /Users/alevitsk/Projects/PermutationSimilarityWebService/docker/data:/data/db
      ports:
        - "27017:27017"
      networks:
        - backend

networks:
  backend: