version: "3.9"
services:
  mongo:
      image: mongo:5.0.3
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
      volumes:
        - ./data/mongodb/:/data/db
      ports:
        - "27017:27017"
      networks:
        - backend

networks:
  backend: